# NEW PROJECT INSTALLATION: docker-compose run --rm web rails new . --force --database=postgresql --skip-bundle
# THIS PROJECT INSTALLATION: docker-compose build web
version: '2'
services:
  db:
    image: postgres
    volumes:
      - ../pg:/var/lib/postgresql/data
  web:
    build: .
    user: dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "80:3000"
    depends_on:
      - db
